### ISSUE TITLE
tic::use_tic() for automatic deployment of pkgdown and testing on AppVeyor

### ISSUE THREAD

**Issue by krlmlr** [jefferislab/RANN#28]
Could you please install

```r
remotes::install_github(c("ropenscilabs/tic", "ropenscilabs/travis"))
```

and run

```r
tic::use_tic()
```

If asked to overwrite `.travis.yml`, select "yes". You may need to set up a Travis access token with `travis::browse_travis_token()` .

Benefits:

1. Automatic building of pkgdown documentation
2. We can build pkgdown for {RANN} and {RANN.L1}  and host in parallel
3. Testing on Windows

I can also do it if you increase my permissions to this repository.

I just noticed {RANN.L1} has been orphaned on CRAN, I'd like to update.

**Comment by krlmlr** [comment]
Thanks for re-inviting me, unfortunately I still can't access the Travis and GitHub configuration from this repository.

With the most recent version of {tic}, you can now do:

```r
tic::use_tic(wizard = FALSE, linux = "travis", mac = "none", windows =
"appveyor", deploy = "travis", matrix = "travis")
```

to either get a quick error, or succeed.

I forgot to mention that you probably also need a GitHub token, create with `usethis::browse_github_token(c("repo", "admin:public_key"))` .

This is a one-off exercise that hopefully will make things easier in the longer run. Thanks for your help!

**Comment by jefferis** [comment]
OK I've done the `tic` setup as requested. Does it look ok?

**Comment by jefferis** [comment]
Hmm there is a build failure – it is unable to install tic at the start of the travis job. 

https://travis-ci.org/jefferislab/RANN/builds/631589524

I have switched the repo to my lab GitHub org (jefferislab) and made you an admin. Perhaps you might be able to debug? The build failure is still there:

https://travis-ci.org/jefferislab/RANN/jobs/631596529

I'm not sure if there could be a PAT issue.

**Comment by jefferis** [comment]
I generated a new PAT (with identical scope) and it looks like the build is running ok now. In any case, I hope you can go ahead and make the changes you would like.

**Comment by krlmlr** [comment]
Thanks, looks good. Do you want to test on AppVeyor too? The configuration has been created, I think you need to register the project with AppVeyor.

I have changed the documentation source to the `gh-pages` branch -- this is now auto-updated by Travis. We can get rid of `docs/` now.

**Comment by krlmlr** [comment]
GitHub Actions would be the way to go these days.
